config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      mount_devise_token_auth_for 'Supplier', at: 'auth'
      resources :orders, only: :index
    end
  end

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :menus, except: :update do
      resources :meals,  only: :create
      resources :orders, only: %i[create edit update destroy]
    end
    get 'users', to: 'users#index'
    root to: 'menus#index'
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    can :manage, Menu if user.admin?
    can :manage, Order, user_id: user.id
    can :read, :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :menu_items,  dependent: :destroy
  has_many :order_items, dependent: :destroy
  has_many :menus,       through:   :menu_items
  has_many :orders,      through:   :order_items

  enum course: %I[first_course main_course beverage]
end

app/models/menu.rb
class Menu < ApplicationRecord
  belongs_to :user

  has_many :menu_items, dependent: :destroy
  has_many :orders,     dependent: :destroy
  has_many :meals,      through:   :menu_items
end

app/models/menu_item.rb
class MenuItem < ApplicationRecord
  belongs_to :menu
  belongs_to :meal
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :menu
  belongs_to :user

  has_many   :order_items, dependent: :destroy
  has_many   :meals,       through:   :order_items

  accepts_nested_attributes_for :order_items
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :meal

  accepts_nested_attributes_for :meal
end

app/models/supplier.rb
class Supplier < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  include DeviseTokenAuth::Concerns::User
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :menus,  dependent: :destroy
  has_many :orders, dependent: :destroy

  before_save :set_admin

  private

  def set_admin
    self.admin = true unless User.exists?
  end
end

app/controllers/api/v1/orders_controller.rb
class Api::V1::OrdersController < ApiApplicationController
  def index
    @order_facade = Order::OrderFacade.new
  end
end

app/controllers/api_application_controller.rb
class ApiApplicationController < ActionController::Base
  protect_from_forgery with: :null_session

  include DeviseTokenAuth::Concerns::SetUserByToken

  skip_before_action :verify_authenticity_token
  before_action      :authenticate_api_v1_supplier!
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :set_locale, :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  include PolicyHandler

  def notify(key, message)
    flash[key] = message
  end

  helper_method :allow_placement?, :allow_modification?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit :sign_up,        keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end

  private

  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end

  def default_url_options(options = {})
    { locale: I18n.locale }.merge options
  end

  def added_attrs
    %i[name email password password_confirmation remember_me]
  end
end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def create
    meal = Meal::Create.call(
      meal_params: params[:meal],
      form:        meal_form,
      menu:        menu
    )

    if meal
      notify(:notice, t('controllers.meals.flash.create'))
    else
      notify(:error, t('controllers.meals.flash.error'))
    end

    redirect_back(fallback_location: root_path)
  end

  private

  def meal_form
    @meal_form ||= MealForm.new(meal: Meal.new, menu_item: MenuItem.new)
  end

  def menu
    @menu ||= Menu.find_by(id: params[:menu_id])
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  load_and_authorize_resource

  def index
    @menus = Menu.all.decorate
  end

  def show
    @facade = Menu::ShowFacade.new(params)
  end

  def new
    @menu = Menu.new
  end

  def create
    menu = Menu::Create.call(current_user)

    notify(:notice, t('controllers.menus.flash.create')) if menu
    redirect_to edit_menu_path menu
  end

  def edit
    @facade = Menu::EditFacade.new(params)
  end

  def destroy
    Menu::Destroy.call(params[:id])

    notify(:notice, t('controllers.menus.flash.destroy'))
    redirect_to menus_path
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  load_and_authorize_resource

  def create
    Order::Create.call(
      params: order_params,
      user:   current_user,
      menu:   menu
    )

    redirect_to menu
  end

  def edit
    @order ||= Order.find_by(id: params[:id])
  end

  def update
    Order::Update.call(
      id:     params[:id],
      params: order_params,
      menu:   menu
    )

    notify(:notice, t('controllers.orders.flash.update'))
    redirect_to menu
  end

  def destroy
    Order::Destroy.call(params[:id])

    notify(:notice, t('controllers.orders.flash.destroy'))
    redirect_to menu
  end

  private

  def menu
    @menu ||= Menu.find_by(id: params[:menu_id])
  end

  def order_params
    params.require(:order).permit(order_items_attributes: %i[meal_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/_auth.html.haml
%p
  - if user_signed_in?
    = "Logged in as #{current_user.name}"
    %br
    = link_to 'Edit profile', edit_user_registration_path
    |
    = link_to "Log out", destroy_user_session_path, method: :delete
  - else
    = link_to "Sign up", new_user_registration_path
    |
    = link_to "Log in", new_user_session_path

app/views/application/_flash.html.haml
- flash.each do |flash_type, message|
  = content_tag :div, message, class: flash_type

app/views/application/_navbar.html.haml
%nav
  = link_to "English", locale: :en unless current_page?(locale: :en)
  = link_to "Українська", locale: :uk unless current_page?(locale: :uk)

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{charset: "utf-8"}
    %meta{name: "viewport", content: "width=device-width, initial-scale=1.0"}
    %title LunchSelector
    = csrf_meta_tags

    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'vendor/modernizr'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

  %body.row
    %h1.text-center.main-title= t('views.layouts.title')
    .text-right
      = render 'application/navbar'
      = render 'application/flash'
      = render 'application/auth'
    = yield

app/views/meals/_courses.html.haml
%h3= t courses.context[:course]
= render partial: 'meals/meal', collection: facade.courses[courses_counter], locals: { facade: facade }

app/views/meals/_form.html.haml
%h3= t('views.meals.add')
= form_for [menu, meal] do |f|
  .row
    .medium-6.column
      = f.label Meal.human_attribute_name('name')
      = f.text_field :name
  .row
    .medium-6.column
      = f.radio_button :course, :first_course
      = f.label Meal.human_attribute_name('first_course')
      = f.radio_button :course, :main_course
      = f.label Meal.human_attribute_name('main_course')
      = f.radio_button :course, :beverage
      = f.label Meal.human_attribute_name('beverage')
  .row
    .medium-6.column
      = f.label MenuItem.human_attribute_name('price')
      = f.number_field :price
  .row
    .medium-6.column
      = f.submit class: 'button expand'

app/views/meals/_meal.html.haml
%p= "#{meal.name} - #{number_to_currency(meal.todays_price(facade.menu))}"

app/views/meals/_meal_list.html.haml
%h4 first_course
= render partial: 'meals/meal', collection: first_course, locals: { menu: menu }
%br
%h4 main_course
= render partial: 'meals/meal', collection: main_course, locals: { menu: menu }
%br
%h4 beverage
= render partial: 'meals/meal', collection: beverage, locals: { menu: menu }
%br

app/views/menus/_form.html.haml
.text-center
  = form_for(menu) do |f|
    = f.submit class: 'button warning large expand'

app/views/menus/_menu.html.haml
%li= link_to menu.day_stamp, menu_path(menu)

app/views/menus/edit.html.haml
%h2= t('views.menus.menu')

= render partial: 'meals/courses', collection: @facade.courses, locals: { facade: @facade }

- if allow_modification?(@facade.menu)
  = render 'meals/form', menu: @facade.menu, meal: @facade.new_meal

= link_to t('views.done'), menu_path(@facade.menu), class: 'button success'

app/views/menus/index.html.haml
%h2= t('views.menus.list')
%ul
  = render @menus

- if current_user.admin?
  = link_to t('views.menus.new'), new_menu_path if allow_placement?(@menus.last)
  %br
  = link_to t('views.all_users'), users_path

app/views/menus/new.html.haml
%h1= t('views.menus.new')
= render 'form', menu: @menu

app/views/menus/show.html.haml
%h2= "Menu for #{@facade.menu.day_stamp}"
%h3= t('views.menus.orders')

%ul
  = render partial: 'orders/order', collection: @facade.orders, as: :order, locals: { facade: @facade }

%p= "#{t('views.menus.total_cost')}: #{number_to_currency(@facade.total_cost)}" if @facade.show_price?(current_user)

- if @facade.placed_order?(current_user)
  %p Your order has been placed
- elsif allow_modification?(@facade.menu)
  = render 'orders/form', order: @facade.new_order

.button-group
  - if current_user.admin?
    = link_to t('views.menus.manage_meals'), edit_menu_path(@facade.menu), class: 'button success'
    = link_to t('views.menus.delete'), menu_path(@facade.menu), method: :delete, class: 'button alert'
  %br
  = link_to t('views.menus.dashboard'), menus_path, class: 'button'

app/views/orders/_form.html.haml
%h1= t('views.orders.select_meals')
= form_for [order.menu, order] do |f|
  .row
    .medium-6.column
      = f.fields_for :order_items do |oif|
        = oif.select :meal_id, options_from_collection_for_select(oif.object.meals_for_select, :id, :name), prompt: t('views.orders.meal')
      = f.submit class: 'button expand'

app/views/orders/_meal.html.haml
=" #{meal.name}"

app/views/orders/_order.html.haml
%li
  = "Order for #{order.stamp}:"
  = render partial: 'orders/meal', collection: order.meals
  - if can?(:manage, order.object) && allow_modification?(order.menu)
    |
    = link_to t('views.orders.edit'), edit_menu_order_path(order.menu, order)
    |
    = link_to t('views.orders.delete'), menu_order_path(order.menu, order), method: :delete

app/views/orders/edit.html.haml
%p
  = render 'orders/form', order: @order.decorate

= link_to t('views.orders.delete'), menu_order_path(@order.menu, @order), method: :delete, class: 'button alert'
%br
= link_to t('views.back'), menu_path(@order.menu), class: 'button success'

app/views/users/_user.html.haml
%li= "#{user.name} - #{user.email}"

app/views/users/index.html.haml
%h3= t('views.all_users')

%ol
  = render @users

%br
= link_to t('views.menus.dashboard'), menus_path